import { Customer } from '../types/customer';
import { GeneralNote } from '../types/note';

export const CAMBODIAN_PROVINCES = [
  { km: 'រាជធានីភ្នំពេញ', en: 'Phnom Penh' },
  { km: 'ខេត្តកណ្ដាល', en: 'Kandal' },
  { km: 'ខេត្តសៀមរាប', en: 'Siem Reap' },
  { km: 'ខេត្តបាត់ដំបង', en: 'Battambang' },
  { km: 'ខេត្តកំពង់ចាម', en: 'Kampong Cham' },
  { km: 'ខេត្តព្រះសីហនុ', en: 'Preah Sihanouk' },
  { km: 'ខេត្តកំពត', en: 'Kampot' },
  { km: 'ខេត្តតាកែវ', en: 'Takeo' },
  { km: 'ខេត្តបន្ទាយមានជ័យ', en: 'Banteay Meanchey' },
  { km: 'ខេត្តកំពង់ធំ', en: 'Kampong Thom' },
  { km: 'ខេត្តកំពង់ឆ្នាំង', en: 'Kampong Chhnang' },
  { km: 'ខេត្តកំពង់ស្ពឺ', en: 'Kampong Speu' },
  { km: 'ខេត្តព្រៃវែង', en: 'Prey Veng' },
  { km: 'ខេត្តស្វាយរៀង', en: 'Svay Rieng' },
  { km: 'ខេត្តពោធិ៍សាត់', en: 'Pursat' },
  { km: 'ខេត្តកោះកុង', en: 'Koh Kong' },
  { km: 'ខេត្តកែប', en: 'Kep' },
  { km: 'ខេត្តប៉ៃលិន', en: 'Pailin' },
  { km: 'ខេត្តព្រះវិហារ', en: 'Preah Vihear' },
  { km: 'ខេត្តស្ទឹងត្រែង', en: 'Stung Treng' },
  { km: 'ខេត្តក្រចេះ', en: 'Kratie' },
  { km: 'ខេត្តរតនគិរី', en: 'Ratanakiri' },
  { km: 'ខេត្តមណ្ឌលគិរី', en: 'Mondulkiri' },
  { km: 'ខេត្តឧត្ដរមានជ័យ', en: 'Oddar Meanchey' },
  { km: 'ខេត្តត្បូងឃ្មុំ', en: 'Tboung Khmum' },
];

export interface CambodianVillage {
  id: string;
  num: string;
  name: string;
  fullName: string;
  en: string;
}

export const CAMBODIAN_VILLAGES: CambodianVillage[] = [
  { id: '1', num: '១', name: 'ចំបក់ស', fullName: 'ភូមិចំបក់ស', en: 'Chambak Sa' },
  { id: '2', num: '២', name: 'គោកដូង', fullName: 'ភូមិគោកដូង', en: 'Kok Doung' },
  { id: '3', num: '៣', name: 'ស្វាយ', fullName: 'ភូមិស្វាយ', en: 'Svay' },
  { id: '4', num: '៤', name: 'តាហុក', fullName: 'ភូមិតាហុក', en: 'Ta Hok' },
  { id: '5', num: '៥', name: 'ធិបតី', fullName: 'ភូមិធិបតី', en: 'Thipadei' },
  { id: '6', num: '៦', name: 'ជួយចក្រី', fullName: 'ភូមិជួយចក្រី', en: 'Chuoy Chakkrei' },
  { id: '7', num: '៧', name: 'ឈូក', fullName: 'ភូមិឈូក', en: 'Chhouk' },
  { id: '8', num: '៨', name: 'ត្រីញ័រ', fullName: 'ភូមិត្រីញ័រ', en: 'Trei Nhor' },
  { id: '9', num: '៩', name: 'ធ្វាស', fullName: 'ភូមិធ្វាស', en: 'Thveas' },
  { id: '10', num: '១០', name: 'ត្រពាំងព្រីង', fullName: 'ភូមិត្រពាំងព្រីង', en: 'Trapeang Pring' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-debt-1',
    name: 'អ៊ុំ សារ៉េត',
    phone: '097 554 1122',
    address: 'ចំបក់ស',
    province: 'ខេត្តសៀមរាប',
    date: '2026-10-02',
    note: 'ទិញសម្ភារ និងជីកសិកម្មជំពាក់សិន។ បានសន្យាសងបញ្ចប់នៅចុងខែក្រោយ។',
    status: 'debt',
    category: 'retail',
    priority: 'medium',
    telegram: '0975541122',
    balance: 450.00,
    currency: 'USD',
    history: [
      {
        id: 'hist-d-1',
        content: 'បានកត់ត្រាប័ណ្ណជំពាក់ថ្លៃជីកសិកម្ម $450',
        createdAt: '2026-10-02T10:00:00Z',
      }
    ],
    createdAt: '2026-10-02T10:00:00Z',
    updatedAt: '2026-10-02T10:00:00Z',
  },
  {
    id: 'cust-1',
    name: 'ឈន ពិសិដ្ឋ',
    phone: '012 889 977',
    address: 'ផ្ទះលេខ 45B ផ្លូវ 271 សង្កាត់បឹងទំពុន ខណ្ឌមានជ័យ',
    province: 'រាជធានីភ្នំពេញ',
    date: '2026-10-01',
    note: 'អតិថិជនកម្ម៉ង់ទំនិញគ្រឿងអេឡិចត្រូនិចបោះដុំចំនួន ២០ ឈុត។ ដឹកជញ្ជូនរៀងរាល់ដើមខែ និងទូទាត់តាម ABA។',
    status: 'active',
    category: 'wholesale',
    priority: 'high',
    email: 'piseth.chhorn@gmail.com',
    telegram: '@piseth_biz',
    balance: 1450.00,
    currency: 'USD',
    history: [
      {
        id: 'hist-1-1',
        content: 'បានទូទាត់ប្រាក់កក់ $500 រួចរាល់តាម ABA Pay',
        createdAt: '2026-10-01T09:30:00Z',
      },
      {
        id: 'hist-1-2',
        content: 'បានបញ្ជាក់ការដឹកជញ្ជូនលើកទី ១ នៅថ្ងៃទី ០៥ ខាងមុខ',
        createdAt: '2026-10-02T08:15:00Z',
      }
    ],
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-10-02T08:15:00Z',
  },
  {
    id: 'cust-2',
    name: 'សុខ សុវណ្ណារ៉ា',
    phone: '098 554 433',
    address: 'ភូមិវត្តបូព៌ សង្កាត់សាលាកំរើក ក្រុងសៀមរាប',
    province: 'ខេត្តសៀមរាប',
    date: '2026-10-02',
    note: 'អតិថិជន VIP ប្រចាំហាង កក់សេវាកម្មជួសជុល និងតម្លើងប្រព័ន្ធកាមេរ៉ាសុវត្ថិភាព។ បានណែនាំមិត្តភក្តិ ៣ នាក់មកបន្ថែម។',
    status: 'active',
    category: 'vip',
    priority: 'high',
    email: 'sovannara.sok@yahoo.com',
    telegram: '@sok_sovannara',
    balance: 820.00,
    currency: 'USD',
    history: [
      {
        id: 'hist-2-1',
        content: 'បានទាក់ទងមកពិភាក្សាអំពីកិច្ចសន្យាថែទាំប្រចាំឆ្នាំ',
        createdAt: '2026-10-02T11:00:00Z',
      }
    ],
    createdAt: '2026-09-20T14:20:00Z',
    updatedAt: '2026-10-02T11:00:00Z',
  },
  {
    id: 'cust-3',
    name: 'កែវ សុផល',
    phone: '077 321 654',
    address: 'ផ្លូវជាតិលេខ 5 ភូមិព្រែកមហាទេព ក្រុងបាត់ដំបង',
    province: 'ខេត្តបាត់ដំបង',
    date: '2026-09-28',
    note: 'កម្ម៉ង់គ្រឿងបន្លាស់ម៉ាស៊ីន និងសម្ភារសំណង់។ កំពុងរង់ចាំការបញ្ជាក់ពីអ្នកផ្គត់ផ្គង់ខាងភ្នំពេញ។',
    status: 'pending',
    category: 'retail',
    priority: 'medium',
    telegram: '077321654',
    balance: 350.00,
    currency: 'USD',
    history: [
      {
        id: 'hist-3-1',
        content: 'បានផ្ញើតារាងតម្លៃតាម Telegram ជូនអតិថិជនពិនិត្យ',
        createdAt: '2026-09-28T16:00:00Z',
      }
    ],
    createdAt: '2026-09-28T15:30:00Z',
    updatedAt: '2026-09-29T10:00:00Z',
  },
  {
    id: 'cust-4',
    name: 'ហេង ម៉េងហុង',
    phone: '085 990 011',
    address: 'ផ្សារលើធំថ្មី ផ្លូវឯករាជ្យ សង្កាត់លេខ ៤ ក្រុងព្រះសីហនុ',
    province: 'ខេត្តព្រះសីហនុ',
    date: '2026-09-25',
    note: 'បានបញ្ចប់គម្រោងដំឡើងកុំព្យូទ័រ និងបណ្ដាញ Network ការិយាល័យ។ បានទូទាត់ប្រាក់គ្រប់ចំនួនរួចរាល់។',
    status: 'completed',
    category: 'service',
    priority: 'low',
    email: 'menghong.heng@gmail.com',
    telegram: '@menghong_heng',
    balance: 0.00,
    currency: 'USD',
    history: [
      {
        id: 'hist-4-1',
        content: 'ចុះហត្ថលេខាលើលិខិតប្រគល់-ទទួលការងារ និងចេញប័ណ្ណធានា ១ ឆ្នាំ',
        createdAt: '2026-09-25T17:00:00Z',
      }
    ],
    createdAt: '2026-09-10T09:00:00Z',
    updatedAt: '2026-09-25T17:00:00Z',
  },
  {
    id: 'cust-5',
    name: 'លី ស្រីមុំ',
    phone: '016 778 899',
    address: 'ផ្លូវលេខ ៦៨ ភូមិស្វាយធំ ក្រុងកំពង់ចាម',
    province: 'ខេត្តកំពង់ចាម',
    date: '2026-09-29',
    note: 'កម្ម៉ង់ទំនិញអនឡាញ (សម្លៀកបំពាក់ និងកាបូប)។ ផ្ញើតាមក្រុមហ៊ុន វីរៈប៊ុនថាំ (VET Express) សាខាកំពង់ចាម។',
    status: 'active',
    category: 'online',
    priority: 'medium',
    telegram: '@sreymom_ly',
    balance: 65.00,
    currency: 'USD',
    history: [
      {
        id: 'hist-5-1',
        content: 'បានវេចខ្ចប់ទំនិញ និងផ្ញើលេខកូដដឹកជញ្ជូន VET-88934',
        createdAt: '2026-09-29T13:45:00Z',
      }
    ],
    createdAt: '2026-09-29T11:00:00Z',
    updatedAt: '2026-09-29T13:45:00Z',
  },
  {
    id: 'cust-6',
    name: 'ចាន់ វីរៈ',
    phone: '011 223 344',
    address: 'បុរីពិភពថ្មី ចំការដូង ខណ្ឌដង្កោ',
    province: 'រាជធានីភ្នំពេញ',
    date: '2026-09-15',
    note: 'អតិថិជនចាស់ បច្ចុប្បន្នផ្អាកការកម្ម៉ង់ជាបណ្ដោះអាសន្ន ដោយសារកំពុងរៀបចំផ្លាស់ប្តូរទីតាំងហាងថ្មី។',
    status: 'inactive',
    category: 'retail',
    priority: 'low',
    telegram: '011223344',
    balance: 0.00,
    currency: 'USD',
    history: [],
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-09-15T15:00:00Z',
  },
];

export const INITIAL_NOTES: GeneralNote[] = [
  {
    id: 'note-1',
    title: 'ផែនការផ្គត់ផ្គង់ទំនិញដើមខែតុលា',
    content: 'ពិនិត្យស្តុកទំនិញគ្រឿងអេឡិចត្រូនិចដែលត្រូវបញ្ជូនទៅអតិថិជន ឈន ពិសិដ្ឋ នៅភ្នំពេញ និងរៀបចំវិក្កយបត្រតាម ABA Pay។',
    category: 'ការងារអាជីវកម្ម',
    customerId: 'cust-1',
    customerName: 'ឈន ពិសិដ្ឋ',
    color: 'yellow',
    isPinned: true,
    createdAt: '2026-10-01T08:00:00Z',
    updatedAt: '2026-10-02T09:00:00Z',
  },
  {
    id: 'note-2',
    title: 'ណាត់ជួបក្រុមបច្ចេកទេសសៀមរាប',
    content: 'ណាត់ជួបតេស្តកាមេរ៉ាសុវត្ថិភាពម៉ាក Dahua/Hikvision សម្រាប់ផ្ទះលោក សុខ សុវណ្ណារ៉ា នៅក្រុងសៀមរាប វេលាម៉ោង ២ រសៀល។',
    category: 'បច្ចេកទេស',
    customerId: 'cust-2',
    customerName: 'សុខ សុវណ្ណារ៉ា',
    color: 'blue',
    isPinned: true,
    createdAt: '2026-10-02T07:30:00Z',
    updatedAt: '2026-10-02T07:30:00Z',
  },
  {
    id: 'note-3',
    title: 'លេខទូរស័ព្ទក្រុមហ៊ុនដឹកជញ្ជូនរហ័ស',
    content: '- វីរៈប៊ុនថាំ (VET Express): 023 999 999\n- ជេ អ៊ែន ធី (J&T Express): 023 900 888\n- ខេភី (Capitol Express): 023 217 627',
    category: 'ទូទៅ',
    color: 'green',
    isPinned: false,
    createdAt: '2026-09-25T14:00:00Z',
    updatedAt: '2026-09-25T14:00:00Z',
  },
  {
    id: 'note-4',
    title: 'ពិនិត្យរបាយការណ៍ចំណូលចំណាយចុងខែ',
    content: 'ផ្ទៀងផ្ទាត់សមតុល្យអតិថិជនជំពាក់ និងប្រាក់ដែលបានទូទាត់រួចក្នុងប្រព័ន្ធ សៀវភៅបញ្ជី មុននឹងបិទបញ្ជីខែ។',
    category: 'ហិរញ្ញវត្ថុ',
    color: 'purple',
    isPinned: false,
    createdAt: '2026-09-30T16:00:00Z',
    updatedAt: '2026-09-30T16:00:00Z',
  },
];
